# -*- coding: utf-8 -*-
"""atividade 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e28qSlpuVBhv8Nne_t6ktc2QFzahfIUr

**Respostas da 3° atividade**
"""

#PERGUNTA 1:

# Solicita ao usuário um gênero de filme
print("Opções disponíveis: 1-ação, 2-fantasia, 3-aventura")
genero = int(input())
# Estrutura condicional para verificar a escolha e fazer a recomendação
if genero == 1 :
    print("\n🎬 Recomendação de Ação: 'O legado Bourne'")
elif genero == 2:
    print("\n🎬 Recomendação de Fantasia: 'triologia: O senhor dos anéis'")
elif genero == 3:
    print("\n🎬 Recomendação de Aventura: 'triologia: Star Wars'")
else:
# Caso o usuário digite algo diferente das opções disponíveis
    print("\n❌ Opção inválida. Por favor, reinicie o programa e escolha entre: ação, comédia ou terror.")

#PERGUNTA 2:
# Definindo as listas de palavras para a nossa base de dados
positivas = ["bom", "ótimo"]
negativas = ["ruim", "péssimo"]
opniaoUsuario = input("Digite uma palavra: ")

if opniaoUsuario in positivas:
    print("Positiva")
elif opniaoUsuario in negativas:
    print("Negativa")
else:
    print("Neutro")

#PERGUNTA 3:
USUARIO_CORRETO = "admin"
SENHA_CORRETA = "12345"

usuario = input("Digite o usuário: ")
senha = input("Digite a senha: ")
if usuario == USUARIO_CORRETO and senha == SENHA_CORRETA:
    print("Acesso permitido")
else:
    print("Acesso negado")

#PERGUNTA 4:

notas = []
for i in range(1, 6):
    nota = float(input(f"Digite a {i}ª nota: "))
    notas.append(nota)

media = sum(notas) / len(notas)
if media >= 7:
    print("Aprovado")
else:
    print("Reprovado")

#PERGUNTA 5

mensagem = ""
  # Captura a mensagem, remove os espaços extras e coloca a mensagem em minúsculo
while mensagem != "tchau":
    mensagem = input("Você: ").strip().lower()
    if mensagem == "tchau":
        print("chat encerrado")
        break
    # 2. Verificando o que o usuário digitou
    if mensagem == "oi":
        # 2.1
        print("Bot: Olá! Como posso ajudar?")
    else:
        # 2.3
        print("Não entendi sua mensagem.")

#PERGUNTA 6:
palavras_positivas = ["bom", "ótimo"]
# Variável para contar as palavras
contador_positivas = 0
print("Digite uma palavra por vez. Digite 'sair' quando quiser encerrar.")
#Loop para pedir uma nova palavra e para sair
while True:
    palavra = input("Digite uma palavra: ").strip().lower()
    # Condição para parar o loop
    if palavra == 'sair':
        break
    # Verifica se a palavra está na lista de positivas
    if palavra in palavras_positivas:
        contador_positivas += 1

# Exibe o resultado final
print(f"\nTotal de palavra(s) positiva(s):  {contador_positivas}")

#PERGUNTA 7:
idade = int(input("Digite sua idade: "))
if idade >= 18:
    print("Você tem permissão.")
else:
    print("Você não tem permissão.")