# -*- coding: utf-8 -*-
"""atividade 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e28qSlpuVBhv8Nne_t6ktc2QFzahfIUr

**Respostas da 6° atividade**
"""

#PERGUNTA 1:

# Pergunta sobre o pedido do cliente
pergunta = input("Como posso ajudar com seu pedido na pizzaria? ").lower()


# Processa o que o usuário digitou a apresenta a resposta
if "cardápio" in pergunta or "sabores" in pergunta:
    resposta = "Temos os sabores: Calabresa, Marguerita, Quatro Queijos e Frango com Catupiry."
elif "preço" in pergunta or "valor" in pergunta:
    resposta = "Todas as nossas pizzas grandes custam R$ 50,00."

elif "entrega" in pergunta or "tempo" in pergunta:
    resposta = "O tempo médio da nossa entrega é de 30 a 45 minutos."

else:
    # Se o usuário digitar algo que não foi apresentado
    resposta = "Desculpe, não entendi. Você pode me perguntar sobre o 'cardápio', os 'preços' ou a 'entrega'."


# Mostra a resposta na tela
print(f"Atendente Virtual: {resposta}")

#PERGUNTA 2:
# Apresenta o input para o usuário
palavra = input("Digite uma palavra: ").lower().strip()


# Processa a palavra e exibe a respota
if palavra == "feliz" or palavra == "bom":
    print("Sentimento: Positivo")

elif palavra == "triste" or palavra == "ruim":
    print("Sentimento: Negativo")

else:
    print("Sentimento: Neutro")

#PERGUNTA 3:
genero = input("Digite o seu gênero de filme favorito? (ex: ação, aventura, fantasia): ").strip().lower()

if genero in ["ação", "acao"]:
    filme_recomendado = "O legado Bourne"

elif genero in ["aventura"]:
    filme_recomendado = "O senhor dos anéis"

elif genero in ["fantasia"]:
    filme_recomendado = "Harry Potter"

else:
  filme_recomendado = "Triologia Star wars"

with open("recomendacoes.txt", "a", encoding="utf-8") as arquivo:
    arquivo.write(filme_recomendado + "\n")

#PERGUNTA 4:
import json

# 1. Cria o dicionário usando a função dict()
dados = dict(
    pergunta="Qual é a distância daqui até a Lua?",
    tipo_resposta="curta"
)

# 2. Converte para JSON e exibe na tela (indent=2 faz um recuo menor)
print(json.dumps(dados, indent=2, ensure_ascii=False))

#PERGUNTA 5
# O usuário digita a pergunta
pergunta = input("Digite a sua pergunta: ")

# Salva a pergunta no arquivo
arquivo = open("historico_ia.txt", "a", encoding="utf-8")
arquivo.write(pergunta + "\n")

# fecha o arquivo
arquivo.close()

# Mensagem de sucesso
print("Pergunta salva com sucesso usando o write!")

#PERGUNTA 6:
# O usuário digita
pergunta = input("Pergunta: ").lower().strip()


# Processa a respota
if pergunta == "oi":
    print("IA: Olá!")
elif pergunta == "como você funciona?":
    print("IA: Utilizo programação e IA.")

else:
    # Se não for nenhuma das opções
    print("IA: Não compreendi.")

#PERGUNTA 7:

# Inicia o loop
while True:

    # Deixa o usuário digitar
    pergunta = input("Digite sua pergunta (ou digite 'sair' para encerrar): ").lower().strip()

    # Processa a respota
    if pergunta == "sair":
        print("Programa encerrado. Até logo!")
        break
  # Se o usuário não digitar sair o loop continua
    print("Você perguntou algo! Vamos continuar...\n")

#PERGUNTA 8:

# Deixa o usuário digitar a informação
notas = [float(input(f"Digite a {i+1}ª nota: ")) for i in range(3)]

# Calcula a média
media = sum(notas) / len(notas)

# Define o resultado usando condições em linha (mais compacto)
if media >= 9.0:
    resultado = "Excelente desempenho"
elif media >= 7.0:
    resultado = "Bom desempenho"
else:
    resultado = "Desempenho insuficiente"

print(f"\nMédia: {media:.2f} , resultado: {resultado}")